// Repack only referenced accessors and images; drop superseded arm samplers.
const fs=require('fs'),path=require('path');
const {parseGLB,serializeGLB,sha}=require('./reaper-pipeline/inspect-optimize-glb.cjs');
const base=path.resolve(__dirname,'..'),file=path.join(base,'runtime/reaper-runtime.glb'),bytes=fs.readFileSync(file),{json:j,bin,extraChunks}=parseGLB(bytes);
const oldAccessors=j.accessors,oldViews=j.bufferViews;let removedSamplers=0;
for(const a of j.animations){const ids=[...new Set(a.channels.map(c=>c.sampler))].sort((a,b)=>a-b),map=new Map(ids.map((x,i)=>[x,i]));removedSamplers+=a.samplers.length-ids.length;a.samplers=ids.map(i=>a.samplers[i]);for(const c of a.channels)c.sampler=map.get(c.sampler);}
const used=new Set();for(const m of j.meshes)for(const p of m.primitives){Object.values(p.attributes).forEach(i=>used.add(i));if(p.indices!=null)used.add(p.indices);for(const t of p.targets||[])Object.values(t).forEach(i=>used.add(i));}for(const s of j.skins)used.add(s.inverseBindMatrices);for(const a of j.animations)for(const s of a.samplers){used.add(s.input);used.add(s.output);}
const ids=[...used].sort((a,b)=>a-b),map=new Map(ids.map((x,i)=>[x,i]));
for(const m of j.meshes)for(const p of m.primitives){for(const k of Object.keys(p.attributes))p.attributes[k]=map.get(p.attributes[k]);if(p.indices!=null)p.indices=map.get(p.indices);for(const t of p.targets||[])for(const k of Object.keys(t))t[k]=map.get(t[k]);}for(const s of j.skins)s.inverseBindMatrices=map.get(s.inverseBindMatrices);for(const a of j.animations)for(const s of a.samplers){s.input=map.get(s.input);s.output=map.get(s.output);}
const chunks=[],views=[];let offset=0;const align=n=>(n+3)&~3;
function add(data,meta={}){const pad=align(offset)-offset;if(pad){chunks.push(Buffer.alloc(pad));offset+=pad;}const id=views.length;views.push({...meta,buffer:0,byteOffset:offset,byteLength:data.length});chunks.push(data);offset+=data.length;return id;}
const counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16},sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},audit=[];
j.accessors=ids.map(id=>{const a={...oldAccessors[id]},v=oldViews[a.bufferView];if(a.sparse||v.extensions)throw Error('Unsupported sparse or compressed source');const size=counts[a.type]*sizes[a.componentType];if(!size)throw Error(a.type);const stride=v.byteStride||size,start=(v.byteOffset||0)+(a.byteOffset||0),length=(a.count-1)*stride+size,source=bin.subarray(start,start+length);if(source.length!==length)throw Error('Truncated accessor');const data=Buffer.alloc(a.count*size);for(let k=0;k<a.count;k++)source.copy(data,k*size,k*stride,k*stride+size);const meta={...(v.target?{target:v.target}:{})};a.bufferView=add(data,meta);delete a.byteOffset;audit.push({originalAccessor:id,accessor:map.get(id),dataSHA256:sha(data),bytes:data.length});return a;});
for(const i of j.images){const v=oldViews[i.bufferView];i.bufferView=add(bin.subarray(v.byteOffset||0,(v.byteOffset||0)+v.byteLength));}
j.bufferViews=views;j.buffers=[{byteLength:offset}];const out=serializeGLB(j,Buffer.concat(chunks),extraChunks);fs.writeFileSync(file,out);
const report={method:'Remove unused animation samplers and unreachable accessors, repack exact byte ranges of each remaining accessor and image. Preserve all live geometry, animation, joint, inverse-bind and texture values.',before:{bytes:bytes.length,sha256:sha(bytes)},after:{bytes:out.length,sha256:sha(out)},removedSamplers,removedAccessors:oldAccessors.length-j.accessors.length,liveAccessorChecksums:audit};fs.writeFileSync(path.join(base,'reaper-compaction.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({before:report.before,after:report.after,removedSamplers,removedAccessors:report.removedAccessors}));
