const fs=require('fs'),path=require('path'),crypto=require('crypto');
const base=path.resolve(__dirname,'..'),req=require('module').createRequire(path.join(require('./resolve-deps.cjs')(__dirname),'package.json'));
const{NodeIO}=req('@gltf-transform/core'),{ALL_EXTENSIONS}=req('@gltf-transform/extensions'),{MeshoptDecoder}=req('meshoptimizer'),T=req('three');
const{sampleSkinnedBounds}=require('./reaper-pipeline/sample-skinned-bounds.cjs');
const read=n=>JSON.parse(fs.readFileSync(path.join(base,n))),write=(n,x)=>fs.writeFileSync(path.join(base,n),JSON.stringify(x,null,2)+'\n'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),record=n=>{const bytes=fs.readFileSync(path.join(base,n));return{path:n,bytes:bytes.length,sha256:sha(bytes)}};
(async()=>{
 await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder});
 const source=read('inventory.json').assets.find(a=>a.slug==='reaper'),settings=read('runtime-config.json').reaper,opt=read('optimized/reaper/reaper-runtime.report.json'),exclusions=read('reaper-grounding-exclusions.json'),originalSamples=sampleSkinnedBounds(await io.read(path.join(base,'runtime/reaper-runtime.glb')),T,65,exclusions),variants={},qa={sampleCountPerClip:65,sampleCountTotal:1560,exclusions,variants:{}};
 write('reaper-pose-samples.json',originalSamples);
 const compactValidation=v=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k,{numErrors:x.numErrors,numWarnings:x.numWarnings,numInfos:x.numInfos,numHints:x.numHints,codes:x.messages.reduce((o,m)=>(o[m.code]=(o[m.code]||0)+1,o),{}),examples:[...new Map(x.messages.map(m=>[m.code,m])).values()]}]));
 let sampled;
 for(const v of opt.variants){if(v.validation.direct.numErrors||v.validation.decoded.numErrors)throw Error('Validation failed');const n='optimized/reaper/'+v.filename,bytes=fs.readFileSync(path.join(base,n));if(sha(bytes)!==v.sha256)throw Error('Checksum mismatch');const d=await io.readBinary(bytes);sampled=sampleSkinnedBounds(d,T,65,exclusions);const checks={};let maxSampleDifference=0;
  for(const c of sampled.clips){for(const [i,s]of c.samples.entries()){if(!s.bounds.min.every(Number.isFinite)||!s.bounds.max.every(Number.isFinite))throw Error('Nonfinite pose');const prev=originalSamples.clips.find(x=>x.name===c.name).samples[i];for(const k of ['min','max'])for(let a=0;a<3;a++)maxSampleDifference=Math.max(maxSampleDifference,Math.abs(s.bounds[k][a]-prev.bounds[k][a]));}checks[c.name]={duration:c.duration,minimumY:c.minimumVertexY,maxExtent:Math.max(...c.samples.flatMap(s=>s.bounds.size)),maximumFloorLift:Math.max(0,sampled.rest.bounds.min[1]-c.minimumVertexY)};}
  if(maxSampleDifference>1e-5)throw Error('Packaging changed pose bounds');const key=v.name==='mobile1024'?'mobile':'hd';variants[key]={...record(n),textureCap:v.textureCap,validationErrors:0};qa.variants[key]={sha256:v.sha256,validation:compactValidation(v.validation),maxSampleDifference,clips:checks};
 }
 const grounding={restMinY:sampled.rest.bounds.min[1],clips:Object.fromEntries(sampled.clips.map(c=>[c.name,c.samples.map(s=>s.bounds.min[1])]))};write('reaper-grounding.json',{reaper:grounding});write('reaper-grounding-qa.json',qa);
 const{style,...manifestSettings}=settings;
 const entry={...manifestSettings,equipment:'embedded',contactSockets:'embedded',contentVersion:'recovered-september9-v1',sourceAssetId:source.sourceArtwork.assetId,sourceJobId:source.jobId,sourceMeshSha256:source.sha256,sourceCreatedAt:source.createdAt,bounds:sampled.rest.bounds,variants,grounding,derivation:'recovered-provider-mesh-with-continuous-garment-skinning-and-native-motion-constrained-to-two-hand-scythe-grip',geometry:{sourceTriangles:59342,hdTriangles:59342,mobileTriangles:59342,sourceTopologyPreserved:true},contacts:['ContactBase','ContactTip']};
 write('reaper-manifest-entry.json',entry);
 const contacts={};for(const c of sampled.clips.filter(c=>['side','diagonal','backhand','overhead'].includes(c.name))){const phase=entry.contactPhase[c.name],active=c.samples.map((s,i)=>({fraction:i/64,...s.keyNodePositions})).filter(s=>s.fraction>=phase[0]&&s.fraction<=phase[1]);contacts[c.name]={phase,duration:c.duration,maxForwardReach:Math.max(...active.flatMap(s=>[s.ContactBase[2],s.ContactTip[2]])),samples:active};}write('reaper-contact-qa.json',{units:'unscaled source glTF meters; configured height scale = height/rest bounds sizeY',configuredHeight:settings.height,configuredScale:settings.height/sampled.rest.bounds.size[1],sockets:read('derived/reaper-rigging.json').contactSockets,clips:contacts,limitation:'Exact blade endpoints; CPU measurements do not replace actual game collision tests.'});
 const rt=read('runtime/reaper-retargeted.retarget-report.json');
 const summary={schemaVersion:1,slug:'reaper',status:'prepared-for-runtime-contact-test',original:record('models/reaper-original.glb'),rigged:record('derived/reaper-reskinned.glb'),runtime:record('runtime/reaper-runtime.glb'),variants,sourceTriangles:59342,sourceVertices:38028,provenance:'reaper-provenance.json',rig:rt.rig,clips:rt.clips.map(c=>({name:c.name,duration:c.outputDurationSeconds,source:c.provenance})),bounds:sampled.rest.bounds,sockets:read('derived/reaper-rigging.json').contactSockets,reskin:read('reaper-reskin-qa.json'),grip:read('reaper-grip-qa.json'),compaction:'reaper-compaction.json',grounding:'reaper-grounding.json',groundingQA:'reaper-grounding-qa.json',contactQA:'reaper-contact-qa.json',validationErrors:0,visualQA:{walking:'review/reaper-final-gait/gait-contact-sheet.png',actions:'review/reaper-final-actions/action-contact-sheet.png'},limits:['Uniform65-sample floor curve; no continuous-extrema proof','Native one-hand donor arm motion is locally constrained to preserve both hands on original diagonal scythe','Flowing lower robe follows Hips; it is not simulated cloth','Both texture variants retain all59342 source triangles; mobile is a texture-size optimization']};write('reaper-build-summary.json',summary);
 fs.writeFileSync(path.join(base,'reaper.SHA256SUMS'),[summary.original,summary.rigged,summary.runtime,...Object.values(variants)].map(x=>x.sha256+'  '+x.path).join('\n')+'\n');console.log(JSON.stringify({variants,rest:sampled.rest.bounds,maxSampleDifference:Math.max(...Object.values(qa.variants).map(v=>v.maxSampleDifference)),contacts:Object.fromEntries(Object.entries(contacts).map(([n,c])=>[n,c.maxForwardReach]))},null,2));
})().catch(e=>{console.error(e.stack);process.exitCode=1});
