from pathlib import Path
import json,math
ROOT=Path(__file__).resolve().parents[1]
rows=[
('dusk-rogue','+Z',None,'No held weapon; quiver and back straps retained.','Keep runtime held blade.','No severe static silhouette issue observed.'),
('ember-dragon','+Z','both claws','Wings, tail, wrist cuffs and hanging chains retained.','Use true claw geometry for contact; wings/tail/chains need intentional weights.','Wing tips/thin membranes and chains need animated review; no static omission identified.'),
('frost-mage','+Z','RightHand','Complete blue-crystal staff retained.','Disable added staff; rigidly bind retained staff and place muzzle at real crystal.','Thin shaft requires exact rigid prop mask; three source rigged models have only a static pose.'),
('goblin','+X','RightHand','Cleaver retained.','Disable added cleaver; use blade geometry for contact.','No severe static silhouette issue observed; prior local interpretation differs visibly.'),
('knife-rogue','+X',None,'Bandolier knives and waist/sheath details retained; hands empty.','Keep runtime handheld dagger.','Cloth is a single reconstructed surface; animated shoulders/hem need review.'),
('lich','+X','RightHand','Complete purple-crystal staff retained.','Disable added staff; rigidly bind retained staff and place muzzle at real crystal.','Thin crown/robe tips and long shaft need deformation review.'),
('lion-knight','+Z',None,'Back-slung sword retained; hands empty.','Keep runtime handheld sword; do not rebind decorative back sword to attacking hand.','Source rig is static 24-joint; back sword should follow torso.'),
('ogre','+X','RightHand','Spiked club retained.','Disable added club; rigidly bind recovered club and derive contact from spikes/head.','No severe static silhouette issue observed; prior local interpretation differs visibly.'),
('ranger','+X','LeftHand','Bow, string and back quiver retained.','Keep bow attached to LeftHand; align projectile spawn with retained bow.','Thin bow/string must not deform with torso; cape edge needs movement review.'),
('reaper','+X','RightHand primary; LeftHand lower grip','Complete scythe held diagonally across body; right hand near blade, left hand at lower shaft.','Use recovered scythe without prior old-mesh repair; rigid primary-hand binding plus matching off-hand placement/animation.','Thin robe tails and scythe blade tips need masks; source side view hides broad blade, frontal view confirms it.'),
('sage','+X','LeftHand','Complete amber staff retained in left hand.','Disable added right-hand staff; bind actual staff to LeftHand and update muzzle/animation handedness.','Critical difference from previous runtime staff convention; cannot reuse RightHand muzzle blindly.'),
('silver-knight','+X',None,'Left-hip/sheath sword detail retained; hands appear open, no held blade.','Keep runtime handheld sword; leave hip sword with body.','Cape/armor surfaces coherent in static front/quarter/back; joint deformation unverified.'),
('skeleton-warrior','+X','RightHand sword; LeftHand shield','Complete sword and painted round shield retained.','Disable both added sword and shield; rigidly bind each to its actual hand.','Thin forearms/ribs and weapon crossings need careful weights; do not classify shield as body.'),
('spider','+X','fangs','Eight-leg silhouette, eyes, palps and fangs retained.','Use custom eight-leg skeleton; no humanoid rig.','Leg segment correspondence and feet/fangs require animated review.')]
items=[]
for slug,forward,hand,equipment,recommendation,concern in rows:
 items.append({'slug':slug,'sourceForwardGltf':forward,'canonicalYawRadians':0 if forward=='+Z' else -math.pi/2,'canonicalYawDegrees':0 if forward=='+Z' else -90,'heldEquipmentHand':hand,'observedEquipment':equipment,'integrationRecommendation':recommendation,'reviewLimitOrConcern':concern,'comparisonImage':str(ROOT/'review'/f'{slug}-comparison.jpg'),'viewsInspected':['aligned-front','aligned-quarter','aligned-back','previous-runtime-quarter']})
report={'schemaVersion':1,'coordinateConvention':'glTF +Y up and target +Z forward. Source +X maps to target +Z with -90 degrees about glTF +Y, equivalent to Blender +Z. Originals are not rotated.','method':'Actual original GLBs imported into bpy 5.2.1 and rendered in neutral Cycles lighting, 8 samples, 320x420 per panel. Rest pose only. Previous runtime model panel excludes game-added props. Frames are independently fitted to imported scene bounds; apparent screen size is not a physical-size comparison.','models':items,'notClaimed':['No continuous deformation/contact validation performed by this static audit.','No runtime performance validation from studio images.','No automatic proof that provider rigs correctly weight held equipment.'],'hashInvariant':'Original files remain byte-identical to inventory.json; any rigging, equipment rebind or orientation correction must be a derived output.'}
(ROOT/'visual-review.json').write_text(json.dumps(report,indent=2)+'\n')
md=['# Recovered model static review','','Actual original GLBs were reviewed from front, quarter and back against the previous runtime geometry. Previous runtime views exclude game-added equipment. This is static asset review, not animation/contact acceptance.','','All ten Tripo originals face glTF **+X**: rotate **−90° about glTF +Y** into canonical +Z. The four standard-provider outputs face +Z already. Originals remain unmodified.','','| Character | Source facing | Retained equipment / hand | Runtime action |','|---|---|---|---|']
for x in items:md.append(f"| {x['slug']} | {x['sourceForwardGltf']} | {x['observedEquipment']} | {x['integrationRecommendation']} |")
md+=['','The **Sage is left-handed with the staff**, while Frost Mage and Lich hold theirs in the right hand. The recovered Reaper uses a complete diagonal scythe with both hands, unlike the prior repaired T-pose source. Weapon sockets must be derived from these actual meshes.','','See `visual-review.json`, `original-metadata.json` and `review/*-comparison.jpg` for exact evidence and limitations.']
(ROOT/'visual-review.md').write_text('\n'.join(md)+'\n')
for slug in ['ogre','goblin','skeleton-warrior','reaper']:
 for old,new in [('recovered-front','raw-camera-plus-z'),('recovered-quarter','raw-camera-plus-x-plus-z'),('recovered-back','raw-camera-minus-z')]:
  a=ROOT/'review'/f'{slug}-{old}.png';b=ROOT/'review'/f'{slug}-{new}.png'
  if a.exists() and not b.exists():a.rename(b)
p=ROOT/'README.md';s=p.read_text().replace('Raw Tripo humanoids inspected so far face glTF +X.','All ten raw Tripo models, including the spider, face glTF +X.').replace('Final per-character visual findings are recorded separately after every view is inspected.','All fourteen per-character findings are recorded in `visual-review.json` and `visual-review.md`.');p.write_text(s)
print(json.dumps({'reviewedModels':len(items),'review':str(ROOT/'visual-review.json')}))
