import {test,after} from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import os from 'node:os';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const game=process.env.GAME_ROOT||process.cwd(),outputDir=process.env.CHARACTER_QA_OUT||path.join(os.tmpdir(),'ashen-character-low-qa');await mkdir(outputDir,{recursive:true});
const {build}=await import(pathToFileURL(path.join(game,'node_modules/esbuild/lib/main.js'))),{MeshoptDecoder}=await import(pathToFileURL(path.join(game,'node_modules/meshoptimizer/index.js')));await MeshoptDecoder.ready;
const bundle=path.join(outputDir,'character-low-presentation.mjs');await build({stdin:{contents:'export * from "./app/game/character-assets";export * from "./app/game/combat";export {knight} from "./app/game/character-skins";export {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";export * as T from "three";',resolveDir:game},outfile:bundle,nodePaths:[path.join(game,'node_modules')],bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'candidate-presentation',setup(b){if(process.env.SOLE_CACHE)b.onResolve({filter:/foot-contact-cache\.json$/},()=>({path:path.resolve(process.env.SOLE_CACHE)}));if(process.env.PRESENTATION_SOURCE)b.onResolve({filter:/character-presentation$/},()=>({path:path.resolve(process.env.PRESENTATION_SOURCE)}));}}]});
const {T,GLTFLoader,knight,installActorVisual,STRIKES,strikeDuration,CHARACTER_MANIFEST_URL}=await import(pathToFileURL(bundle));
const manifest=JSON.parse(await readFile(path.join(game,'public',CHARACTER_MANIFEST_URL))),templates=new Map(),footCache=new Map();
const cacheInput=process.env.SOLE_CACHE||path.join(game,'app/game/foot-contact-cache.json');
const report={cacheInput,cacheSha256:createHash('sha256').update(await readFile(cacheInput)).digest('hex'),manifest:CHARACTER_MANIFEST_URL,tier:'low',visibleLOD:0,headlessMethod:'Original loaded Low GLB BIN, compression, geometry, skin, hierarchy and animation bytes retained. Only image/material JSON bindings removed for headless GLTFLoader.',assets:[],planting:[],weapon:[],windupReset:[],nonmonotonic:[],limits:'Geometry support checks cover rigid knee-bound vertices in the bottom 0.28 model metres; no GPU texture/render validation or physical-device performance claims.'};
function geometryOnly(bytes){const size=bytes.readUInt32LE(12),j=JSON.parse(bytes.subarray(20,20+size)),bin=bytes.subarray(28+size);delete j.materials;delete j.textures;delete j.images;delete j.samplers;for(const mesh of j.meshes)for(const p of mesh.primitives)delete p.material;for(const key of ['extensionsRequired','extensionsUsed'])j[key]=(j[key]??[]).filter(x=>x!=='KHR_texture_basisu');const json=Buffer.from(JSON.stringify(j)),pad=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(pad);const out=Buffer.alloc(28+pad.length+bin.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(pad.length,12);out.writeUInt32LE(0x4e4f534a,16);pad.copy(out,20);out.writeUInt32LE(bin.length,20+pad.length);out.writeUInt32LE(0x004e4942,24+pad.length);bin.copy(out,28+pad.length);return out.buffer.slice(out.byteOffset,out.byteOffset+out.byteLength);}
for(const id of ['ash-knight','crypt-warden','ember-sovereign']){const variant=manifest.characters[id].variants.low,bytes=await readFile(path.join(game,'public',variant.url)),sha=createHash('sha256').update(bytes).digest('hex');assert.equal(sha,variant.sha256);const gltf=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(geometryOnly(bytes),'');templates.set(id,gltf);report.assets.push({id,url:variant.url,sha256:sha,bytes:bytes.length,clips:gltf.animations.map(a=>a.name)});}
function make(id){const actor=knight(id!=='ash-knight',id==='ember-sovereign');installActorVisual(actor,templates.get(id));actor.group.position.set(3,.6,-2);actor.group.rotation.y=.43;actor.visual.lod(0,300);actor.group.updateMatrixWorld(true);return actor;}
const segment=a=>{const b=new T.Vector3(),t=new T.Vector3();a.visual.segment(b,t);return[b,t];};
const trs=n=>({p:n.position.clone(),q:n.quaternion.clone(),s:n.scale.clone()});
function sameTRS(n,b,message){assert.ok(n.position.distanceTo(b.p)<1e-8,message+' position');assert.ok(n.quaternion.toArray().every((v,i)=>Math.abs(v-b.q.toArray()[i])<1e-8),message+' rotation');assert.ok(n.scale.distanceTo(b.s)<1e-8,message+' scale');}
function feet(id,actor){if(footCache.has(id))return footCache.get(id);const raw=[[],[]],v=new T.Vector3();actor.group.traverse(mesh=>{if(!mesh.isSkinnedMesh)return;let n=mesh,level;while(n&&n!==actor.group){if(Number.isInteger(n.userData.lod)){level=n.userData.lod;break;}n=n.parent;}if(level!==0)return;const pos=mesh.geometry.attributes.position,j=mesh.geometry.attributes.skinIndex,w=mesh.geometry.attributes.skinWeight;if(!j||!w)return;for(let side=0;side<2;side++){const ji=mesh.skeleton.bones.findIndex(b=>b.name===`${side?'right':'left'}_knee`);if(ji<0)continue;for(let i=0;i<pos.count;i++){if(![0,1,2,3].some(k=>j.getComponent(i,k)===ji&&w.getComponent(i,k)>.999))continue;v.fromBufferAttribute(pos,i).applyMatrix4(mesh.bindMatrix).applyMatrix4(mesh.skeleton.boneInverses[ji]);raw[side].push(v.clone());}}});
 const result=raw.map((points,side)=>{assert.ok(points.length>10,'Missing rigid foot geometry');const ys=points.map(p=>p.clone().applyMatrix4(actor.knees[side].matrixWorld).y),min=Math.min(...ys),scale=actor.group.scale.y;return points.filter((_,i)=>ys[i]<min+.28*scale);});footCache.set(id,result);return result;}
const support=(actor,points)=>{actor.group.updateMatrixWorld(true);const v=new T.Vector3();return points.map((leg,i)=>{let min=Infinity;for(const p of leg)min=Math.min(min,v.copy(p).applyMatrix4(actor.knees[i].matrixWorld).y);return min;});};
const modes=[['forward',0,1,0],['backward',0,-1,0],['strafe_left',-1,0,0],['strafe_right',1,0,0],['idle',0,0,0],['turn',0,0,.4]];
for(const id of templates.keys()){
 test(`${id}: loaded Low geometry plants feet with bounded hip-only corrections at 20/30/60/120 FPS`,()=>{
  const record={id,frames:0,rigidFootVertices:[],maximumHipDownMetres:0,maximumHipUpMetres:0,maximumSupportGapMetres:0,minimumFootClearanceMetres:Infinity,maximumBodyDelta:0,maximumWeaponDelta:0,maximumSampledHipDriftMetres:0};
  for(const fps of [20,30,60,120])for(const [mode,x,z,turn] of modes){const actor=make(id),pure=make(id),points=feet(id,actor),scale=actor.group.scale.y;record.rigidFootVertices=points.map(p=>p.length);actor.group.userData.localMoveX=x;actor.group.userData.localMoveZ=z;actor.group.userData.turn=turn;pure.group.userData.localMoveX=x;pure.group.userData.localMoveZ=z;pure.group.userData.turn=turn;
   const duration=templates.get(id).animations.find(c=>c.name===mode).duration,moving=['idle','turn'].includes(mode)?0:1;
   for(let frame=0;frame<=Math.ceil(duration*fps);frame++){const age=Math.min(duration-1e-6,frame/fps);actor.visual.beginFrame();actor.visual.locomotion(age,moving);pure.visual.locomotion(age,moving);for(let side=0;side<2;side++){const drift=actor.legs[side].position.distanceTo(pure.legs[side].position);record.maximumSampledHipDriftMetres=Math.max(record.maximumSampledHipDriftMetres,drift);assert.ok(drift<1e-7,'Previous presentation offset leaked into next animation sample');}actor.group.updateMatrixWorld(true);const roots=[actor.group,actor.body,actor.torso,actor.arms[1],actor.elbows[1],actor.wrists[1],actor.sword].map(n=>[n,trs(n)]),beforeWeapon=segment(actor),hips=actor.legs.map(n=>n.getWorldPosition(new T.Vector3()));
    actor.visual.present(1/fps,.6,true);const afterWeapon=segment(actor),heights=support(actor,points),minimum=(Math.min(...heights)-.6)/scale;
    for(const[n,t]of roots)sameTRS(n,t,`${id} ${mode} ${fps}fps protected transform`);
    for(let side=0;side<2;side++){const p=actor.legs[side].getWorldPosition(new T.Vector3()),dy=(p.y-hips[side].y)/scale;assert.ok(Math.abs(p.x-hips[side].x)<1e-7&&Math.abs(p.z-hips[side].z)<1e-7,'Hip correction changes only world vertical');assert.ok(dy>=-.1250001&&dy<=.0400001,'Hip correction exceeded bounds');record.maximumHipDownMetres=Math.max(record.maximumHipDownMetres,-dy);record.maximumHipUpMetres=Math.max(record.maximumHipUpMetres,dy);const delta=beforeWeapon[side].distanceTo(afterWeapon[side]);record.maximumWeaponDelta=Math.max(record.maximumWeaponDelta,delta);assert.ok(delta<1e-7,'Planting moved weapon');}
    record.maximumSupportGapMetres=Math.max(record.maximumSupportGapMetres,minimum);record.minimumFootClearanceMetres=Math.min(record.minimumFootClearanceMetres,minimum);record.frames++;
    assert.ok(minimum>=-.005,`${id} ${mode} ${age}: penetration ${minimum}`);assert.ok(minimum<=.0050001,`${id} ${mode} ${age}: hovering ${minimum}`);
   }actor.visual.dispose();pure.visual.dispose();
  }report.planting.push(record);
 });
 test(`${id}: all strike contacts and body roots remain exact at 20/30/60/120 FPS`,()=>{
  let samples=0,maxSocketDelta=0;
  for(const fps of [20,30,60,120])for(const authored of STRIKES)for(const enemyTiming of [false,true]){const strike=enemyTiming?{...authored,windup:id==='ember-sovereign'?.80:.55,active:authored.active*(id==='ember-sovereign'?1.2:1),recovery:authored.recovery*(id==='ember-sovereign'?1.15:1)}:authored,actor=make(id),pure=make(id);
   actor.visual.beginFrame();actor.visual.locomotion(.25,.8);actor.visual.present(1/fps,.6,false);
   const times=new Set([strike.windup,strike.windup+strike.active/2,strike.windup+strike.active-1e-6]);for(let t=0;t<=strikeDuration(strike);t+=1/fps)times.add(t);
   for(const age of [...times].sort((a,b)=>a-b)){actor.visual.beginFrame();actor.visual.locomotion(age,.8);actor.visual.strike(strike,age);pure.visual.strike(strike,age);const before=segment(actor),reference=segment(pure),body=trs(actor.body),group=trs(actor.group);actor.visual.present(1/fps,.6,false);const after=segment(actor);
    if(age>=strike.windup&&age<strike.windup+strike.active){sameTRS(actor.body,body,'Active body protected');sameTRS(actor.group,group,'Actor group protected');for(let i=0;i<2;i++){const delta=Math.max(before[i].distanceTo(after[i]),reference[i].distanceTo(after[i]));maxSocketDelta=Math.max(maxSocketDelta,delta);assert.ok(delta<1e-7,`${id} ${authored.id} ${fps}fps at ${age}: ${delta}`);}samples++;}
   }actor.visual.dispose();pure.visual.dispose();
  }report.weapon.push({id,activeSamples:samples,maxSocketDeltaMetres:maxSocketDelta});
 });
 test(`${id}: installation/reset in every initial windup preserves sampled arms and removes presentation history`,()=>{
  let cases=0;for(const fps of [20,30,60,120])for(const strike of STRIKES)for(const reset of [false,true]){const actor=make(id);if(reset){actor.visual.beginFrame();actor.visual.locomotion(.4,.8);actor.visual.present(1/fps,.6,false);actor.visual.resetPresentation();}actor.visual.beginFrame();actor.visual.strike(strike,strike.windup*.3);const arm=trs(actor.arms[1]),body=trs(actor.body),before=segment(actor);actor.visual.present(1/fps,.6,false);sameTRS(actor.arms[1],arm,'Initial windup arm');sameTRS(actor.body,body,'Initial windup body');const after=segment(actor);for(let i=0;i<2;i++)assert.ok(before[i].distanceTo(after[i])<1e-7);actor.visual.resetPresentation();actor.visual.beginFrame();actor.visual.locomotion(0,0);actor.visual.present(1/fps,.6,true);const fresh=make(id);fresh.visual.beginFrame();fresh.visual.locomotion(0,0);fresh.visual.present(1/fps,.6,true);for(const[a,b]of [[actor.body,fresh.body],[actor.arms[1],fresh.arms[1]],...actor.legs.map((n,i)=>[n,fresh.legs[i]])])sameTRS(a,trs(b),'Reset matches fresh');actor.visual.dispose();fresh.visual.dispose();cases++;}report.windupReset.push({id,cases});
 });
 test(`${id}: extra nonmonotonic collision samples never advance presentation or leak between instances`,()=>{
  const a=make(id),b=make(id),s=STRIKES[0];for(const actor of[a,b]){actor.visual.beginFrame();actor.visual.locomotion(.4,.8);actor.visual.present(1/60,.6,false);actor.visual.beginFrame();actor.visual.locomotion(.42,.8);}for(const t of[.05,.19,.03,.12,.06])a.visual.strike(s,t);for(const actor of[a,b]){actor.visual.strike(s,.06);actor.visual.present(1/60,.6,false);}for(const[x,y]of [[a.body,b.body],[a.arms[1],b.arms[1]],[a.legs[0],b.legs[0]],[a.knees[1],b.knees[1]]])sameTRS(x,trs(y),'Nonmonotonic sample independence');a.visual.dispose();b.visual.dispose();report.nonmonotonic.push({id,passed:true});
 });
}
test('all Low archetypes: 200 repeated idle and forward samples do not accumulate foot or cape offsets',()=>{
 for(const id of templates.keys())for(const moving of [0,1]){
  const actor=make(id),pure=make(id);let cape,referenceCape;actor.group.traverse(n=>{if(n.name==='cape_lower')cape=n;});pure.group.traverse(n=>{if(n.name==='cape_lower')referenceCape=n;});
  let firstSoles;const points=feet(id,actor);
  for(let frame=0;frame<200;frame++){
   actor.visual.beginFrame();actor.visual.locomotion(.25,moving);pure.visual.locomotion(.25,moving);
   for(let side=0;side<2;side++)sameTRS(actor.legs[side],trs(pure.legs[side]),'Constant sampled hip stays pure');
   if(cape)sameTRS(cape,trs(referenceCape),'Constant sampled cape stays pure');
   actor.visual.present(1/60,.6,false);const heights=support(actor,points);if(!firstSoles)firstSoles=heights;for(let side=0;side<2;side++)assert.ok(Math.abs(heights[side]-firstSoles[side])<1e-7,'Foot accumulates during constant pose');
   if(cape){const qa=cape.quaternion.clone().normalize(),qb=referenceCape.quaternion.clone().normalize();assert.ok(qa.angleTo(qb)<=.045001,'Cape offset accumulated beyond bounded follow');}
  }
  actor.visual.resetPresentation();if(cape)sameTRS(cape,trs(referenceCape),'Reset restores cape source');actor.visual.dispose();pure.visual.dispose();
 }
});

after(async()=>{await writeFile(path.join(outputDir,'character-low-qa.json'),JSON.stringify(report,null,2)+'\n');});
