import fs from 'node:fs';import {createRequire} from 'node:module';import {pathToFileURL,fileURLToPath} from 'node:url';import path from 'node:path';import os from 'node:os';import {test,after} from 'node:test';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const game=path.resolve(process.env.GAME_ROOT||fileURLToPath(new URL('../',import.meta.url))),fixture=fileURLToPath(new URL('./fixtures/gait-baseline/',import.meta.url)),out=process.env.GAIT_QA_OUT?path.resolve(process.env.GAIT_QA_OUT):fs.mkdtempSync(path.join(os.tmpdir(),'ashen-gait-qa-'));fs.mkdirSync(out,{recursive:true});const require=createRequire(path.join(game,'package.json'));const {build}=require('esbuild'),{MeshoptDecoder}=require('meshoptimizer');await MeshoptDecoder.ready;
const modules={};for(const candidate of [false,true]){const source=candidate?path.join(game,'app/game'):fixture;const dest=out+'/'+(candidate?'candidate':'baseline')+'.mjs';await build({stdin:{contents:'export * from "./app/game/character-assets";export * from "./app/game/combat";export {knight} from "./app/game/character-skins";export {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";export * as T from "three";',resolveDir:game},outfile:dest,nodePaths:[game+'/node_modules'],bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'proposal',setup(b){b.onLoad({filter:/\.ts\.fixture$/},args=>({contents:fs.readFileSync(args.path,'utf8'),loader:'ts'}));b.onResolve({filter:/^\.\//},args=>{const base=args.path.replace(/^\.\//,'');if(['character-assets','character-presentation','gait-contact','gait-contact-cache.json'].includes(base)||base==='app/game/character-assets')return{path:source+'/'+(base==='app/game/character-assets'?'character-assets':base)+(base.endsWith('.json')?'':candidate?'.ts':'.ts.fixture')};if(args.importer.startsWith(fixture)&&!base.startsWith('node_modules'))return{path:game+'/app/game/'+base+(/\.(json|ts)$/.test(base)?'':'.ts')};});}}]});modules[candidate?'candidate':'baseline']=await import(pathToFileURL(dest));}
const manifest=JSON.parse(fs.readFileSync(game+'/public'+modules.candidate.CHARACTER_MANIFEST_URL)),soles=JSON.parse(fs.readFileSync(game+'/app/game/foot-contact-cache.json'));
function geometryOnly(bytes){const size=bytes.readUInt32LE(12),j=JSON.parse(bytes.subarray(20,20+size)),bin=bytes.subarray(28+size);delete j.materials;delete j.textures;delete j.images;delete j.samplers;for(const m of j.meshes)for(const p of m.primitives)delete p.material;for(const k of ['extensionsRequired','extensionsUsed'])j[k]=(j[k]??[]).filter(x=>x!=='KHR_texture_basisu');const text=Buffer.from(JSON.stringify(j)),pad=Buffer.alloc(Math.ceil(text.length/4)*4,32);text.copy(pad);const b=Buffer.alloc(28+pad.length+bin.length);b.writeUInt32LE(0x46546c67,0);b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(pad.length,12);b.writeUInt32LE(0x4e4f534a,16);pad.copy(b,20);b.writeUInt32LE(bin.length,20+pad.length);b.writeUInt32LE(0x004e4942,24+pad.length);bin.copy(b,28+pad.length);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
const inputs={};const names=['ash-knight','crypt-warden','ember-sovereign'];for(const id of names){const v=manifest.characters[id].variants.low,bytes=fs.readFileSync(game+'/public'+v.url),sha256=createHash('sha256').update(bytes).digest('hex');assert.equal(sha256,v.sha256,'Low asset hash mismatch: '+id);inputs[id]={url:v.url,sha256};}const templates={};for(const [kind,m]of Object.entries(modules)){templates[kind]={};for(const id of names)templates[kind][id]=await new m.GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(geometryOnly(fs.readFileSync(game+'/public'+manifest.characters[id].variants.low.url)),'');}
const scenarios=[['forward',0,1,0],['backward',0,-1,0],['strafe_left',-1,0,0],['strafe_right',1,0,0],['curved_forward',0,1,.65],['diagonal',Math.SQRT1_2,Math.SQRT1_2,0],['turn',0,0,.65]];
const rows=[];
test('all Low rigs: 84 distance-calibrated stance routes preserve world roots and reduce sliding at 20/30/60/120 FPS',()=>{
for(const id of names)for(const fps of [20,30,60,120])for(const [mode,dx,dz,turn] of scenarios){
 const row={id,fps,mode};
 for(const [kind,m]of Object.entries(modules)){const {T,knight,installActorVisual}=m,actor=knight(id!=='ash-knight',id==='ember-sovereign');installActorVisual(actor,templates[kind][id]);const scale=actor.group.scale.y,points=soles[id].map(leg=>leg.map(p=>new T.Vector3().fromArray(p))),centers=points.map(p=>p.reduce((s,v)=>s.add(v),new T.Vector3()).divideScalar(p.length));
 const dt=1/fps,speed=id==='ash-knight'?5.4:id==='crypt-warden'?2.35:2.4,motion=mode==='turn'?0:id==='ash-knight'?1:.8;
 let previousSide=-1,previousCenter=new T.Vector3(),drifts=[],runTravel=0,maxRunTravel=0,minClearance=Infinity,maxSupportGap=0,maxHipXZ=0,maxHipDown=0;actor.group.position.set(2,.6,-3);actor.group.rotation.y=.43;
 for(let i=0;i<Math.ceil(3*fps);i++){actor.visual.beginFrame();actor.group.rotation.y+=turn*dt;const yaw=actor.group.rotation.y;actor.group.position.x+=(dx*Math.cos(yaw)+dz*Math.sin(yaw))*speed*dt;actor.group.position.z+=(-dx*Math.sin(yaw)+dz*Math.cos(yaw))*speed*dt;actor.group.userData.localMoveX=dx;actor.group.userData.localMoveZ=dz;actor.group.userData.turn=turn;
 actor.visual.locomotion(i*dt,motion);actor.group.updateMatrixWorld(true);const before=actor.legs.map(l=>l.getWorldPosition(new T.Vector3())),root=actor.group.matrixWorld.clone(),body=actor.body.position.clone(),base=new T.Vector3(),tip=new T.Vector3();actor.visual.segment(base,tip);actor.visual.present(dt,.6,true);actor.group.updateMatrixWorld(true);const afterBase=new T.Vector3(),afterTip=new T.Vector3();actor.visual.segment(afterBase,afterTip);assert.ok(base.distanceTo(afterBase)<1e-7&&tip.distanceTo(afterTip)<1e-7,'Stance changed weapon chain');assert.ok(actor.body.position.distanceTo(body)<1e-8,'Stance changed body');assert.deepEqual(actor.group.matrixWorld.elements,root.elements,'Stance changed actor root');
 const ys=points.map((ps,k)=>Math.min(...ps.map(p=>p.clone().applyMatrix4(actor.knees[k].matrixWorld).y))),side=ys[0]<=ys[1]?0:1,c=centers[side].clone().applyMatrix4(actor.knees[side].matrixWorld);minClearance=Math.min(minClearance,(Math.min(...ys)-.6)/scale);maxSupportGap=Math.max(maxSupportGap,(Math.min(...ys)-.6)/scale);
 for(let k=0;k<2;k++){const after=actor.legs[k].getWorldPosition(new T.Vector3());maxHipXZ=Math.max(maxHipXZ,Math.hypot(after.x-before[k].x,after.z-before[k].z)/scale);maxHipDown=Math.max(maxHipDown,(before[k].y-after.y)/scale);}
 if(i>fps*.5&&side===previousSide){const delta=Math.hypot(c.x-previousCenter.x,c.z-previousCenter.z);drifts.push(delta/dt);runTravel+=delta;maxRunTravel=Math.max(maxRunTravel,runTravel);}else runTravel=0;previousSide=side;previousCenter.copy(c);
 }
 drifts.sort((a,b)=>a-b);row[kind]={meanXZMetresPerSecond:drifts.reduce((s,v)=>s+v,0)/drifts.length,medianXZMetresPerSecond:drifts[Math.floor(drifts.length*.5)],p95XZMetresPerSecond:drifts[Math.floor(drifts.length*.95)],sameSupportMaxTravelMetres:maxRunTravel,minClearanceModelMetres:minClearance,maxSupportGapModelMetres:maxSupportGap,maxHipXZModelMetres:maxHipXZ,maxHipDownModelMetres:maxHipDown,samples:drifts.length};actor.visual.dispose();
 }
 row.medianImprovement=1-row.candidate.medianXZMetresPerSecond/Math.max(.0001,row.baseline.medianXZMetresPerSecond);row.meanImprovement=1-row.candidate.meanXZMetresPerSecond/Math.max(.0001,row.baseline.meanXZMetresPerSecond);assert.ok(row.candidate.maxHipXZModelMetres<=.180001);assert.ok(row.candidate.maxHipDownModelMetres<=.180001);assert.ok(row.candidate.minClearanceModelMetres>=-.005&&row.candidate.maxSupportGapModelMetres<=.005001);if(mode!=='turn')assert.ok(row.meanImprovement>=.7,'Translated support motion not reduced enough');rows.push(row);
}
assert.equal(rows.length,84);});
const contactRows=[];test('all Low rigs: 48 translated strike routes preserve active contacts and reset cleanly at 20/30/60/120 FPS',()=>{for(const [kind,m]of Object.entries(modules))if(kind==='candidate')for(const id of names)for(const fps of [20,30,60,120])for(const strike of m.STRIKES){const actor=m.knight(id!=='ash-knight',id==='ember-sovereign');m.installActorVisual(actor,templates[kind][id]);const v=m.T.Vector3,dt=1/fps;let maximum=0;actor.group.position.set(2,.6,-3);for(let age=0;age<m.strikeDuration(strike)+dt;age+=dt){actor.visual.beginFrame();actor.group.position.z+=.05;actor.group.rotation.y+=.012;actor.visual.locomotion(age,.8);actor.visual.strike(strike,age);const b=new v(),t=new v();actor.visual.segment(b,t);const body=actor.body.position.clone(),q=actor.body.quaternion.clone();actor.visual.present(dt,.6,false);const bb=new v(),tt=new v();actor.visual.segment(bb,tt);if(age>=strike.windup&&age<strike.windup+strike.active){maximum=Math.max(maximum,b.distanceTo(bb),t.distanceTo(tt));assert.ok(maximum<1e-7);assert.ok(actor.body.position.distanceTo(body)<1e-8&&actor.body.quaternion.angleTo(q)<1e-6);}}actor.visual.resetPresentation();actor.visual.beginFrame();actor.visual.locomotion(0,0);actor.visual.present(dt,.6,true);for(const bone of actor.legs)assert.ok(bone.position.toArray().every(Number.isFinite));actor.visual.dispose();contactRows.push({id,fps,strike:strike.id,maximumSocketDeltaMetres:maximum});}
assert.equal(contactRows.length,48);});
after(()=>{const report={manifest:modules.candidate.CHARACTER_MANIFEST_URL,inputs,soleCacheSha256:createHash('sha256').update(fs.readFileSync(game+'/app/game/foot-contact-cache.json')).digest('hex'),baseline:'tests/fixtures/gait-baseline (pre-distance adapter/presentation); current shared rig/combat dependencies and actual Low GLB bytes',contactRows,method:'Actual Low GLBs and current/proposed runtime adapter at 20/30/60/120Hz. Root translated at engine speeds and rotated on curved/turn routes. Support leg selected from minimum AFTER-correction sole height, independent of candidate internal contact identity. World XZ motion of fixed sole-proxy centroid measured only on consecutive same-support samples after0.5s warmup. Exact root/body/weapon preservation asserted per frame. Sole centroid motion includes rolling; no physical-device claim.',rows};fs.writeFileSync(out+'/stance-comparison.json',JSON.stringify(report,null,2));console.log(JSON.stringify({routes:rows.length,contactRoutes:contactRows.length,minimumMovingMeanDriftReduction:Math.min(...rows.filter(r=>r.mode!=='turn').map(r=>r.meanImprovement)),report:path.join(out,'stance-comparison.json')}));});
