"use client";
import { useState, useEffect, useLayoutEffect, useRef, useCallback } from 'react';
import Image from 'next/image';
import { ArrowRight, BookOpen, Check, ChevronRight, Cloud, CloudOff, Compass, Crown, Flame, FlaskConical, LoaderCircle, Maximize, Menu, RotateCcw, Settings2, Shield, Sparkles, Sword, Volume2, VolumeX, Zap } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Progress as ProgressBar } from '@/components/ui/progress';
import { WORLD, level, damage, maxHealth, objective, upgradeCost, type Progress } from './model';
import type { GameEngine, Hud, GameEvent } from './engine';
import { TouchControls } from './TouchControls';
import { initialQuality, SaveQueue } from './mobile-runtime';
import { ROOMS, CORRIDORS, GATES, gateOpen, roomAt } from './dungeon';
import './game.css';
import './mobile.css';

type SaveResponse={guest?:boolean;state?:Progress|null;revision:number;error?:string;conflict?:boolean};
type Modal=''|'settings'|'controls'|'character'|'journal'|'map'|'pause'|'keeper'|'death'|'victory'|'recovery';
function RealmMark({small=false}:{small?:boolean}){return <span className={'realm-mark '+(small?'small':'')} aria-hidden="true"><Flame strokeWidth={1.1}/></span>;}
function WorldMap({p,enemies=[],large=false}:{p:Progress,enemies?:{x:number,z:number}[],large?:boolean}){
 const pos=(x:number,z:number)=>({x:80+x*1.4,y:8+(z+82)*.94});const player=pos(p.x,p.z),current=roomAt(p.x,p.z);
 return <svg className={large?'world-map large':'world-map'} viewBox="0 0 160 160" role="img" aria-label="Dungeon floor plan showing five chambers, locked seals, shrines and your location">
  <rect width="160" height="160" fill="#080f16"/>
  {CORRIDORS.map((r,i)=>{const q=pos(-r.width/2,r.z-r.depth/2);return <rect key={'c'+i} x={q.x} y={q.y} width={r.width*1.4} height={r.depth*.94} fill="#334045"/>;})}
  {ROOMS.map((r,i)=>{const q=pos(-r.width/2,r.z-r.depth/2);return <g key={r.id}><rect x={q.x} y={q.y} width={r.width*1.4} height={r.depth*.94} fill={current?.id===r.id?'#4a4437':'#202b33'} stroke={current?.id===r.id?'#d7bb7d':'#6b7471'} strokeWidth=".7"/>{large&&<text x="112" y={q.y+10} fill="#cfc7b1" fontSize="4">{i+1}. {r.name}</text>}</g>;})}
  {GATES.map((g,i)=>{const q=pos(0,g.z);return <path key={i} d={`M${q.x-5} ${q.y}h10`} stroke={gateOpen(i,p)?'#81b4a3':'#cd795d'} strokeWidth="2"/>;})}
  {WORLD.shrines.map(s=>{const q=pos(s.x,s.z);return <path key={s.id} d={`M${q.x} ${q.y-2}l2 2-2 2-2-2Z`} fill={p.shrines.includes(s.id)?'#92d8e3':'#d8b77e'}/>;})}
  {enemies.map((e,i)=>{const q=pos(e.x,e.z);return <circle key={i} cx={q.x} cy={q.y} r="1.3" fill="#d9816c"/>;})}
  <circle cx={player.x} cy={player.y} r="4.5" fill="#d0f2ec" opacity=".15"/><circle cx={player.x} cy={player.y} r="2" fill="#e0fff5"/>
 </svg>;
}
function Controls(){
 const desktop=[['W A S D / arrows','Move'],['Mouse drag','Look around'],['J / left click','Four-hit sword combo'],['Q','Ember pulse'],['Space','Dodge'],['Shift','Sprint'],['R','Healing flask'],['E','Talk, loot, or rest'],['I / Tab / Esc','Inventory / map / pause']];
 const touch=[['Left thumb pad','Move'],['Push pad to the edge','Sprint'],['Drag the open world','Look around'],['Tap or hold Strike','Four-hit sword combo'],['Tap Ember','Area spell'],['Tap Dodge','Evade before or after a swing'],['Tap Heal','Drink a healing flask'],['Tap the nearby prompt','Talk, loot, or rest'],['Tap your crest / map / ☰','Inventory / map / pause']];
 return <div className="controls-list">{[['desktop-help',desktop],['touch-help',touch]].map(([className,rows])=><div className={className as string} key={className as string}>{(rows as string[][]).map(([key,label])=><div className="control-row" key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div>)}<p className="muted-note">Chain strikes into a side cut, diagonal cut, backhand, and heavier overhead finish. Dodge during the wind-up or recovery; the blade’s contact phase is committed.</p><p className="muted-note touch-help">Keep one thumb on the movement pad while using the action buttons with the other. Landscape gives you more room to see the world.</p></div>;
}

export default function Game(){
 const [playing,setPlaying]=useState(false),[saved,setSaved]=useState<Progress|null>(null),[hud,setHud]=useState<Hud|null>(null),[modal,setModal]=useState<Modal>('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saveStatus,setSaveStatus]=useState('Connecting'),[saveFailed,setSaveFailed]=useState(false),[notice,setNotice]=useState(''),[engineError,setEngineError]=useState(''),[worldReady,setWorldReady]=useState(false);
 const [quality,setQuality]=useState('auto'),[sound,setSound]=useState(true),[preferencesReady,setPreferencesReady]=useState(false),[graphicsRestart,setGraphicsRestart]=useState(0),[name,setName]=useState('The Wanderer'),[confirmNew,setConfirmNew]=useState(false);
 const host=useRef<HTMLDivElement>(null),engine=useRef<GameEngine|null>(null),revision=useRef(0),initial=useRef<Progress|null>(null),saveQueue=useRef(new SaveQueue()),mutationActive=useRef(false),purchaseLock=useRef(false),conflict=useRef(false),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null),milestoneTimer=useRef<ReturnType<typeof setTimeout>|null>(null),saveRef=useRef<()=>Promise<boolean>>(async()=>true),newGameLock=useRef(false);
 const preferences=useRef({quality,sound}),currentModal=useRef(modal);useLayoutEffect(()=>{preferences.current={quality,sound};currentModal.current=modal;},[quality,sound,modal]);
 const p=hud?.p??saved;const quest=p?objective(p):null;const heading=hud?-hud.heading*180/Math.PI:0;const direction=(angle:number)=>['N','NE','E','SE','S','SW','W','NW'][Math.round(((angle%360)+360)%360/45)%8];
 const notify=useCallback((text:string)=>{setNotice(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),5000);},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const res=await fetch('/api/progress',{cache:'no-store'});const data=await res.json() as SaveResponse;if(!res.ok)throw new Error(data.error||'Could not load your journey.');setSaved(data.state??null);revision.current=data.revision;setSaveStatus(data.state?(data.guest?'Guest journey saved':'Journey saved'):(data.guest?'Guest play ready':'Cloud ready'));conflict.current=false;setSaveFailed(false);}catch(e){setError((e as Error).message);setSaveStatus('Cloud unavailable');setSaveFailed(true);}finally{setLoading(false);}},[]);
 useEffect(()=>{const bootstrap=setTimeout(()=>{void load();setQuality(initialQuality(window.matchMedia('(any-pointer: coarse)').matches,()=>localStorage.getItem('ashen-quality-v2')));try{const s=localStorage.getItem('ashen-sound');if(s)setSound(s==='on');}catch{}setPreferencesReady(true);},0);return()=>{clearTimeout(bootstrap);if(noticeTimer.current)clearTimeout(noticeTimer.current);if(milestoneTimer.current)clearTimeout(milestoneTimer.current);};},[load]);
 const save=useCallback(():Promise<boolean>=>{
  if(conflict.current)return Promise.resolve(false);if(mutationActive.current)return Promise.resolve(true);
  return saveQueue.current.run(async()=>{
   if(conflict.current)return false;
   const state=engine.current?.snapshot()??initial.current;if(!state)return true;
   setSaveStatus('Saving');try{const res=await fetch('/api/progress',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:revision.current}),keepalive:true});const d=await res.json() as SaveResponse;if(!res.ok){if(d.conflict)conflict.current=true;throw new Error(d.error||'Save failed.');}revision.current=d.revision;setSaved(state);setSaveStatus(d.guest?'Guest progress saved':'Cloud saved');setSaveFailed(false);return true;}catch(e){setSaveStatus(conflict.current?'Save conflict':'Save failed');setSaveFailed(true);notify((e as Error).message);return false;}
  });
 },[notify]);useLayoutEffect(()=>{saveRef.current=save;},[save]);
 const onEvent=useCallback((e:GameEvent)=>{if(e.type==='notice'&&e.text)notify(e.text);if(e.type==='keeper')setModal('keeper');if(e.type==='death')setModal('death');if(e.type==='victory')setModal('victory');if(e.type==='graphics-lost'){setModal('recovery');void saveRef.current();}if(e.type==='milestone'){if(milestoneTimer.current)clearTimeout(milestoneTimer.current);milestoneTimer.current=setTimeout(()=>void saveRef.current(),700);}},[notify]);
 useEffect(()=>{
  if(!playing||!host.current||!initial.current)return;let active=true;setWorldReady(false);setEngineError('');
  import('./engine').then(({GameEngine})=>{if(!active||!host.current||!initial.current)return;const game=new GameEngine(host.current,initial.current,preferences.current.quality,preferences.current.sound,setHud,onEvent);engine.current=game;game.pause(currentModal.current!=='');setWorldReady(true);if(initial.current.health<=0)setModal('death');else if(graphicsRestart)notify('Graphics restored. Your character’s progress is ready.');else notify('Speak to the Keeper, then descend. Clear each chamber and awaken its shrine.');}).catch(e=>{if(!active)return;console.error(e);setModal('');setEngineError('The 3D world could not start. Try Performance mode to reduce graphics memory. WebGL 2 is required.');});
  return()=>{active=false;engine.current?.dispose();engine.current=null;};
  // Quality and sound update live without recreating the world.
 },[playing,graphicsRestart,onEvent,notify]);
 useEffect(()=>{engine.current?.pause(modal!=='');},[modal,worldReady]);
 useEffect(()=>{
  if(!modal)return;const viewport=window.visualViewport,root=document.documentElement;
  const sync=()=>{root.style.setProperty('--realm-viewport-height',`${viewport?.height??window.innerHeight}px`);root.style.setProperty('--realm-viewport-top',`${viewport?.offsetTop??0}px`);};
  sync();viewport?.addEventListener('resize',sync);viewport?.addEventListener('scroll',sync);
  return()=>{viewport?.removeEventListener('resize',sync);viewport?.removeEventListener('scroll',sync);root.style.removeProperty('--realm-viewport-height');root.style.removeProperty('--realm-viewport-top');};
 },[modal]);
 useEffect(()=>{if(!preferencesReady)return;engine.current?.setQuality(quality);try{localStorage.setItem('ashen-quality-v2',quality);}catch{}},[quality,preferencesReady]);
 useEffect(()=>{if(!preferencesReady)return;engine.current?.setSound(sound);try{localStorage.setItem('ashen-sound',sound?'on':'off');}catch{}},[sound,preferencesReady]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>void saveRef.current(),18000);const hidden=()=>{if(document.hidden){engine.current?.clearInput();setModal(m=>m||'pause');void saveRef.current();}};const hide=()=>void saveRef.current();document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',hide);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',hide);};},[playing]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!playing||modal||['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();if(['escape','i','tab'].includes(k)){e.preventDefault();engine.current?.clearInput();setModal(k==='i'?'journal':k==='tab'?'map':'pause');void saveRef.current();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[playing,modal]);
 async function begin(){if(newGameLock.current)return;newGameLock.current=true;setBusy(true);setError('');try{const res=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'new',name,revision:revision.current})});const d=await res.json() as SaveResponse;if(!res.ok||!d.state)throw new Error(d.error||'Unable to begin your journey.');revision.current=d.revision;conflict.current=false;setSaved(d.state);initial.current=d.state;setHud(null);setSaveFailed(false);setSaveStatus(d.guest?'Guest progress saved':'Cloud saved');setModal('');setGraphicsRestart(0);setPlaying(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);newGameLock.current=false;}}
 function continueGame(){if(!saved)return;initial.current=structuredClone(saved);setHud(null);setModal('');setGraphicsRestart(0);setPlaying(true);}
 async function toTitle(){setBusy(true);if(await save()){const state=engine.current?.snapshot();if(state)setSaved(state);setPlaying(false);setModal('');setHud(null);}setBusy(false);}
 async function upgrade(kind:'blade'|'armor'){if(!engine.current||busy||purchaseLock.current)return;purchaseLock.current=true;setBusy(true);try{if(!await save())return;mutationActive.current=true;const res=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'upgrade',kind,revision:revision.current})});const d=await res.json() as SaveResponse;if(!res.ok||!d.state){if(d.conflict)conflict.current=true;throw new Error(d.error||'Upgrade failed.');}revision.current=d.revision;engine.current?.replace(d.state);setSaved(d.state);setSaveStatus(d.guest?'Guest progress saved':'Cloud saved');notify(kind==='blade'?'Ashen blade strengthened.':'Wanderer armor reinforced.');}catch(e){if(conflict.current){setSaveStatus('Save conflict');setSaveFailed(true);}notify((e as Error).message);}finally{mutationActive.current=false;purchaseLock.current=false;setBusy(false);}}
 function resumeGame(){engine.current?.resumeAudio();setModal('');}
 function changeSound(value:boolean){engine.current?.setSound(value);setSound(value);}
 function restoreGraphics(){const state=engine.current?.snapshot();if(state)initial.current=state;setQuality('low');setWorldReady(false);setEngineError('');setModal('pause');setGraphicsRestart(n=>n+1);}
 function open(m:Modal){engine.current?.clearInput();setModal(m);if(playing)void save();}
 function fullscreen(){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>notify('Use your browser’s full-screen controls.'));}
 const dialogTitle:Record<string,string>={settings:'Shape your experience',controls:'Master blade and flame',character:'Begin a dungeon run',journal:'The wanderer’s journal',map:'The Hollow Crypt',pause:'A moment by the fire',keeper:'The last Keeper',death:'Your ember still burns',victory:'The dawn remembers you',recovery:'Rekindle the world'};
 const dialogDesc:Record<string,string>={settings:'Tune the world to your device.',controls:'Every flame begins with a spark.',character:'Your journey begins at the edge of a forgotten kingdom.',journal:'What you carry. What remains to be done.',map:'Three ancient fires. One hollow crown.',pause:'Your journey waits for you.',keeper:'“Even in the deepest ash, something endures.”',death:'Rise again at your last resting place.',victory:'The Hollow King has fallen. The old fires burn again.',recovery:'Safari interrupted the graphics. Your character’s progress is still here.'};
 return <main className={'game-app '+(playing?'is-playing':'')}>
  {!playing?<section className="title-screen" aria-label="Ashen Realm main menu">
   <Image className="title-art" src="/assets/ashen-realm.webp" alt="A lone knight faces an eclipsed fortress in a ruined mountain kingdom" fill unoptimized priority/>
   <div className="title-shade"/><div className="title-grain"/>
   <header className="title-header"><div className="small-brand"><RealmMark small/><span>ASHEN REALM</span></div><span className="edition">CHAPTER ONE <span> / </span> THE LAST EMBER</span><button className="icon-button header-sound" onClick={()=>changeSound(!sound)} aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></header>
   <div className="title-content"><div className="eyebrow"><span className="short-rule"/> SOLO DUNGEON RPG</div><h1>ASHEN<br/><span>REALM</span></h1><p className="title-subtitle">Five chambers beneath the keep.<br/>One ember to bring home.</p>
    <div className="title-actions"><button className="begin-button" disabled={loading||!!error||busy} onClick={()=>saved?continueGame():setModal('character')}><span>{loading?'Finding your journey':saved?'Continue journey':'Begin dungeon run'}</span>{loading?<LoaderCircle className="spin" size={19}/>:<ArrowRight size={20}/>}</button>
    {saved&&<p className="continue-meta">Level {level(saved)} <span>·</span> {saved.shrines.length} / 3 shrines <span>·</span> {Math.floor(saved.playtime/60)} min played</p>}
    <div className="menu-links">{saved&&<button onClick={()=>{setError('');setModal('character');}}>New dungeon run</button>}<button onClick={()=>open('controls')}>How to play</button><button onClick={()=>open('settings')}>Settings <Settings2 size={14}/></button></div>
    {error&&<div className="menu-error" role="alert"><p>{error}</p><button onClick={()=>void load()}>Reconnect <RotateCcw size={14}/></button></div>}
    </div>
   </div>
   <div className="chapter-card"><span className="chapter-number">01</span><div><p>THE HOLLOW CRYPT</p><span>Five chambers · one final reckoning</span></div><Compass size={26} strokeWidth={1}/></div>
   <footer className="title-footer"><span><span className="tiny-diamond"/> SOLO DUNGEON RUN</span><span className="cloud-state">{saveFailed?<CloudOff size={14}/>:<Cloud size={14}/>} {saveStatus}</span><span>v1.4 <span className="footer-sep">/</span> HEADPHONES RECOMMENDED</span></footer>
  </section>:<>
   <div className="world-host" ref={host}/><div className="world-vignette"/>
   {!worldReady&&!engineError&&<div className="world-loading"><RealmMark/><p>Descending into the Hollow Crypt</p><span>Gathering the last embers…</span><LoaderCircle className="spin" size={20}/></div>}
   {engineError&&<div className="world-loading error-state"><CloudOff/><p>The world could not awaken</p><span>{engineError}</span><button className="primary-action" onClick={restoreGraphics} disabled={busy}>Retry in Performance mode</button><button className="secondary-action" onClick={()=>{if(initial.current)setSaved(structuredClone(initial.current));setPlaying(false);setModal('settings');}}>Back to settings</button></div>}
   {hud&&<div className={"game-hud "+(hud.boss?"has-boss":"")}>
    <div className="player-status"><button className="player-medallion" onClick={()=>open('journal')} aria-label="Open inventory"><RealmMark small/><span>{level(hud.p)}</span></button><div className="vitals"><div className="player-label"><span>{hud.p.name}</span><span>{Math.ceil(hud.p.health)} / {hud.healthMax}</span></div><ProgressBar className="vital-bar health" value={hud.p.health/hud.healthMax*100} aria-label="Health"/><ProgressBar className="vital-bar mana" value={hud.p.mana} aria-label="Mana"/><ProgressBar className="vital-bar stamina" value={hud.stamina} aria-label="Stamina"/></div></div>
    <div className="compass-hud"><div><span>{direction(heading-90)}</span><i/><span>{direction(heading)}</span><i/><span>{direction(heading+90)}</span></div><span className="compass-pin">◇</span><p>{hud.region}</p></div>
    <div className="map-hud"><button onClick={()=>open('map')} aria-label="Open world map"><WorldMap p={hud.p} enemies={hud.enemies}/></button><div><span><Flame size={14}/> {hud.p.souls}</span><button className="icon-button" onClick={()=>open('pause')} aria-label="Pause game"><Menu size={18}/></button></div></div>
    <div className="quest-hud"><p className="eyebrow"><span className="tiny-diamond"/> DUNGEON OBJECTIVE</p><h2>{quest?.title}</h2><p>{quest?.detail}</p><span className="quest-distance"><Compass size={12}/>{Math.round(Math.hypot(hud.p.x-(quest?.x??0),hud.p.z-(quest?.z??0)))} m</span></div>
    {hud.boss&&<div className="boss-status"><span>THE HOLLOW KING</span><ProgressBar className="boss-bar" value={hud.boss.hp/hud.boss.max*100}/><small>{Math.ceil(hud.boss.hp)} / {hud.boss.max}</small></div>}
    {hud.prompt&&<button className="interact-prompt" onClick={()=>engine.current?.interact()}><kbd>E</kbd>{hud.prompt}<ChevronRight size={15}/></button>}
    <div className="desktop-actions"><button onClick={()=>engine.current?.attack()} aria-label="Sword strike, J"><Sword/><kbd>J</kbd><span>Strike</span></button><button onClick={()=>engine.current?.cast()} className={hud.castCd>0||hud.p.mana<25?'cooling':''} aria-label="Ember pulse, Q"><Sparkles/><kbd>{hud.castCd>0?hud.castCd.toFixed(1):'Q'}</kbd><span>Ember pulse</span></button><button onClick={()=>engine.current?.dodge()} className={hud.dodgeCd>0?'cooling':''} aria-label="Dodge, Space"><Zap/><kbd>SPACE</kbd><span>Dodge</span></button><button onClick={()=>engine.current?.heal()} aria-label="Healing flask, R"><FlaskConical/><kbd>R <i>· {hud.p.potions}</i></kbd><span>Crimson flask</span></button><span className="action-divider"/><button onClick={()=>open('journal')} aria-label="Inventory, I"><BookOpen/><kbd>I</kbd><span>Journal</span></button></div>
    <div className="game-bottom"><span className="movement-hint"><kbd>W A S D</kbd> Move <b>·</b> Drag to look</span><button className={'save-indicator '+(saveFailed?'failed':'')} onClick={()=>void save()} aria-label="Save progress now">{saveStatus==='Saving'?<LoaderCircle className="spin" size={13}/>:saveFailed?<CloudOff size={13}/>:<Cloud size={13}/>} {saveStatus}</button><div><button className="icon-button" onClick={()=>changeSound(!sound)} aria-label={sound?'Mute audio':'Enable audio'}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button className="icon-button fullscreen-button" onClick={fullscreen} aria-label="Enter full screen"><Maximize size={16}/></button></div></div>
    <TouchControls engine={engine} hud={hud} active={worldReady&&!modal}/>
    <div className="damage-flash" style={{opacity:hud.damageFlash}}/>
   </div>}
  </>}
  {notice&&<div className="game-notice" role="status"><span className="tiny-diamond"/>{notice}</div>}
  <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!['death','recovery'].includes(modal))resumeGame();}}><DialogContent className={'realm-dialog '+(['journal','map'].includes(modal)?'wide':'')} showCloseButton={!['death','recovery'].includes(modal)}><div className="dialog-eyebrow"><Flame size={14}/> ASHEN REALM</div><DialogTitle className="dialog-title">{dialogTitle[modal]}</DialogTitle><DialogDescription className="dialog-description">{dialogDesc[modal]}</DialogDescription>
   {modal==='character'&&<div className="character-form"><label htmlFor="character-name">Wanderer’s name</label><input id="character-name" value={name} onChange={e=>setName(e.target.value)} maxLength={22} placeholder="The Wanderer" autoComplete="off"/><div className="origin-card"><Shield size={32} strokeWidth={1}/><div><h3>The oathless knight</h3><p>A weathered blade. Three healing flasks.<br/>One descent beneath the Hollow Keep.</p></div></div>{saved&&<p className="muted-note">A new journey will replace your current cloud save.</p>}{error&&<p className="inline-error">{error}</p>}<button className="primary-action" disabled={busy||!name.trim()} onClick={()=>saved?setConfirmNew(true):void begin()}>{busy?<LoaderCircle className="spin" size={16}/>:'Enter the dungeon'}<ArrowRight size={18}/></button></div>}
   {modal==='controls'&&<Controls/>}
   {modal==='settings'&&<div className="settings-form"><div className="setting-row"><div><label id="graphics-label">Graphics quality</label><p>Auto adjusts resolution for your phone. 4K Ultra prioritizes detail.</p></div><Select value={quality} onValueChange={setQuality}><SelectTrigger aria-labelledby="graphics-label"><SelectValue/></SelectTrigger><SelectContent className="realm-select"><SelectItem value="auto">Auto</SelectItem><SelectItem value="low">Performance</SelectItem><SelectItem value="medium">Full HD</SelectItem><SelectItem value="high">4K Ultra</SelectItem></SelectContent></Select></div><div className="setting-row"><div><label htmlFor="sound-switch">Game audio</label><p>Blade impacts, spells, and shrine tones.</p></div><Switch id="sound-switch" checked={sound} onCheckedChange={changeSound}/></div><div className="settings-note"><p>Original browser edition</p><p className="muted-note">No account needed. Guest saves are linked to this browser.</p><span>{hud?`${hud.renderSize.width} × ${hud.renderSize.height} render output`:quality==='auto'?'Adaptive resolution · lighter graphics on mobile':quality==='high'?'4K output · 4096-pixel surface textures':quality==='medium'?'Full HD output · detailed surface textures':'Lower resolution · reduced effects'}</span><p className="credit-links">Dungeon textures by <a href="https://polyhaven.com" target="_blank" rel="noreferrer">Poly Haven ↗</a> · CC0</p></div></div>}
   {modal==='map'&&p&&<div className="map-dialog"><WorldMap p={p} enemies={hud?.enemies} large/><div className="map-legend"><span><i className="legend-player"/> You</span><span><i className="legend-shrine"/> Shrine</span><span><i className="legend-enemy"/> Enemy</span></div><p className="muted-note">Rest at an awakened shrine to restore health, mana, and flasks.</p></div>}
   {modal==='journal'&&p&&<Tabs defaultValue="inventory" className="journal-tabs"><TabsList variant="line"><TabsTrigger value="inventory">Inventory</TabsTrigger><TabsTrigger value="quests">Quests</TabsTrigger><TabsTrigger value="controls">Controls</TabsTrigger></TabsList><TabsContent value="inventory"><div className="character-stats"><div><span>LEVEL</span><strong>{level(p)}</strong></div><div><span>EMBERS</span><strong>{p.souls}</strong></div><div><span>VITALITY</span><strong>{maxHealth(p)}</strong></div><div><span>DAMAGE</span><strong>{damage(p)}</strong></div></div><p className="xp-label">{p.xp%180} / 180 XP to next level</p><ProgressBar value={(p.xp%180)/180*100} className="xp-bar"/>
    <div className="equipment-grid">{(['blade','armor'] as const).map(kind=><article className="equipment-card" key={kind}><div className="equipment-art">{kind==='blade'?<Sword size={66} strokeWidth={.8}/>:<Shield size={66} strokeWidth={.8}/>}</div><span className="item-kind">{kind==='blade'?'WEAPON':'ARMOR'} · RANK {p[kind]+1}</span><h3>{kind==='blade'?'Ashen blade':'Wanderer’s plate'}</h3><p>{kind==='blade'?`${damage(p)} damage per strike`:`${p.armor*3} damage reduction · ${maxHealth(p)} vitality`}</p><button disabled={busy||p[kind]>=4||p.souls<upgradeCost(p[kind])} onClick={()=>void upgrade(kind)}>{p[kind]>=4?'Fully strengthened':<>Strengthen <span><Flame size={13}/>{upgradeCost(p[kind])}</span></>}</button></article>)}</div><div className="flask-row"><FlaskConical size={23}/><div><strong>Crimson flask × {p.potions}</strong><p>Restores 85 health. Refilled at resting places.</p></div></div>
   </TabsContent><TabsContent value="quests"><div className="quest-list"><article className={p.talked?'complete':''}><span>{p.talked?<Check/>:'I'}</span><div><h3>A dying flame</h3><p>Find the Keeper at the first campfire and learn of the old fires.</p></div></article><article className={p.shrines.length===3?'complete':''}><span>{p.shrines.length===3?<Check/>:'II'}</span><div><h3>Kindle the old fires</h3><p>Awaken Cinder, Dusk, and Crown shrines. {p.shrines.length} / 3 lit.</p>{WORLD.shrines.map(s=><small key={s.id}>{p.shrines.includes(s.id)?'◆':'◇'} {s.name}</small>)}</div></article><article className={p.won?'complete':''}><span>{p.won?<Check/>:'III'}</span><div><h3>The hollow crown</h3><p>Break the throne seal and defeat the Hollow King. The flame endures.</p></div></article></div></TabsContent><TabsContent value="controls"><Controls/></TabsContent></Tabs>}
   {modal==='keeper'&&<div className="keeper-dialog"><p>“I have kept this fire for longer than I remember. Beyond this threshold, three shrines lie cold. Cinder. Dusk. Crown.”</p><p>“Defeat each chamber’s wardens and light its shrine to break the next seal. The Hollow King holds the ember that once warmed this kingdom. Take it back.”</p><div className="keeper-tip"><Flame size={20}/><span>Defeat wardens and search relic caches for embers. Strengthen your equipment in the journal. Rest at shrines between encounters.</span></div><button className="primary-action" onClick={resumeGame}>I will carry the flame <ArrowRight size={18}/></button></div>}
   {modal==='pause'&&<div className="pause-actions"><button className="primary-action" onClick={resumeGame}>Return to the dungeon<ArrowRight size={18}/></button><button className="secondary-action" onClick={()=>setModal('journal')}><BookOpen size={18}/>Inventory & quests</button><button className="secondary-action" onClick={()=>setModal('settings')}><Settings2 size={18}/>Settings</button><button className="secondary-action" onClick={()=>void toTitle()} disabled={busy}><Cloud size={18}/>{busy?'Saving journey…':'Save & return to title'}</button>{saveFailed&&<p className="inline-error">{saveStatus==='Save conflict'?'Another tab changed this save. Reload to use the cloud version.':'Your current session is safe here. Retry saving before leaving.'}</p>}</div>}
   {modal==='recovery'&&<div className="ending-panel"><Flame size={52} strokeWidth={.8}/><p>Restore the dungeon with lighter graphics.<br/>Your level, loot, position, and completed objectives stay with you.</p><button className="primary-action" onClick={restoreGraphics} disabled={busy}>Restore in Performance mode<RotateCcw size={18}/></button>{saveFailed&&<p className="inline-error">Saving is unavailable. Keep this page open while restoring graphics.</p>}</div>}
   {modal==='death'&&<div className="ending-panel"><Flame size={52} strokeWidth={.8}/><p>The dungeon has not claimed your ember.<br/>Your level, loot, and quest progress remain.</p><button className="primary-action" onClick={()=>{engine.current?.respawn();resumeGame();}}>Rise from the ashes<RotateCcw size={18}/></button></div>}
   {modal==='victory'&&p&&<div className="ending-panel victory"><Crown size={52} strokeWidth={.8}/><p>Against the silence, you carried the flame.<br/>The Hollow Crypt belongs to the living once more.</p><div className="victory-stats"><span><strong>{level(p)}</strong>LEVEL</span><span><strong>{p.defeated.length}</strong>VANQUISHED</span><span><strong>{Math.floor(p.playtime/60)}m</strong>JOURNEY</span></div><button className="primary-action" onClick={resumeGame}>Explore the cleared dungeon<ArrowRight size={18}/></button><button className="text-action" disabled={busy} onClick={()=>void toTitle()}>Save & return to title</button></div>}
  </DialogContent></Dialog>
  <AlertDialog open={confirmNew} onOpenChange={setConfirmNew}><AlertDialogContent className="realm-dialog"><AlertDialogTitle>Begin a new dungeon run?</AlertDialogTitle><AlertDialogDescription>Your current character and progress will be replaced. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep my journey</AlertDialogCancel><AlertDialogAction onClick={()=>void begin()}>Begin new journey</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
