"""Record immutable source receipts and hash the reviewed derivative package."""
import os,json,hashlib,pathlib,datetime
P=pathlib.Path(os.environ.get('SHRINE_OUT',pathlib.Path(__file__).parent))
def hash_file(name):
 p=P/name;b=p.read_bytes();return {'file':name,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def write(name,data):(P/name).write_text(json.dumps(data,indent=2)+'\n')
op=json.loads((P/'cloud-operation.json').read_text());assert op['terminal'] and op['operation']['status']=='succeeded'
manifest=json.loads((P/'runtime-manifest.json').read_text());audit=json.loads((P/'final-export-audit.json').read_text())
for name,size in [('cloud-source.blend',1215694),('cloud-source.glb',471572),('cloud-source-review.png',683261)]:assert (P/name).stat().st_size==size
for file,key in [('ember-shrine.glb','sha256'),('ember-shrine-fallback.glb','fallbackSha256')]:assert hash_file(file)['sha256']==manifest['primary'][key]
entry={'compressed_url':'/assets/props/v2/ember-shrine.glb','fallback_url':'/assets/props/v2/ember-shrine-fallback.glb','sha256':manifest['primary']['sha256'],'fallback_sha256':manifest['primary']['fallbackSha256'],'source_project_id':'02f9af38-c881-4c8b-9fd6-0cbe6e8f1d59','source_revision':1}
write('manifest-entry.json',entry)
write('placement-contract.json',{'root':'EmberShrine_Runtime','root_transform':'identity','axes':'glTF +Y up, metres','origin':'ground centre','anchors_gltf':manifest['anchors_gltf'],'anchor_tolerance':1e-5,'maximum_footprint_m':3.6,'lod_groups':[{'name':f'EmberShrine_LOD{i}','extras':{'lod':i},'meshes':[f'EmberShrine_LOD{i}_body',f'EmberShrine_LOD{i}_ember']} for i in range(3)],'mesh_extras':{'surface_role':'body or ember','lod_index':'0,1 or2'},'preserve_node_matrices':True,'state_material':'Shrine_StateEmber','runtime_lights':0,'runtime_flames':0,'placement':'at existing shrine root [s.x,0,s.z], unit scale; preserve existing flame, light, interaction and checkpoint entities'})
versions={}
module_dir=pathlib.Path('/Users/nathaniel/Documents/ChatGPT/Knight/game/node_modules')
for name in ['@gltf-transform/core','@gltf-transform/functions','@gltf-transform/extensions','meshoptimizer','sharp','gltf-validator']:
 versions[name]=json.loads((module_dir/name/'package.json').read_text())['version']
ledger={
 'asset_id':'A02_ember_shrine','status':'reviewed ready for integration','recorded_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'workspace':{'id':'bdeb1056-93d9-4c2d-8b80-389d588bab2f','selected':True,'private':True,'owned':True,'plan':'ultimate'},
 'authorization':{'total_higgsfield_credit_ceiling':1000,'scope':'shared across all authorized asset jobs','max_authoring_attempts_per_asset':2,'a02_authoring_attempts_used':1,'no_catalog_or_external_inputs':True},
 'credits':{'before_project_creation':4113.5,'after_project_creation_before_authoring':4113.5,'after_terminal_authoring':4113.5,'after_terminal_checked_utc':'2026-09-09T22:31:12Z','observed_asset_debit':0,'prior_sconce_pilot_observed_debit':0,'interpretation':'Observed balance delta, not quoted operation price or promise of free subsequent jobs. Shared budget owner tracks other assets.','serialized_handoff':'A03 agent notified only after operation terminal and fresh after-balance checkpoint.'},
 'cloud':{'project_id':'02f9af38-c881-4c8b-9fd6-0cbe6e8f1d59','project_url':op['projectUrl'],'revision':1,'scene_sequence':0,'active_operation_id_after_completion':None,'operation_id':op['operation']['id'],'status':op['operation']['status'],'created_at':op['operation']['createdAt'],'started_at':op['operation']['startedAt'],'finished_at':op['operation']['finishedAt'],'artifacts':op['operation']['artifacts'],'exact_operation_record':'cloud-operation.json'},
 'source':{'authorship':'Original assistant-authored bpy geometry and procedural materials created in the user-owned Higgsfield project; no external mesh/texture/catalog/reference inputs.','author_code':hash_file('author_shrine.py'),'committed_blend':hash_file('cloud-source.blend'),'committed_glb':hash_file('cloud-source.glb'),'committed_render':hash_file('cloud-source-review.png'),'mesh_parts':63,'evaluated_triangles':8128,'source_glb_limitation':'Procedural shader texture appearance is absent from raw cloud GLB. Runtime appearance comes from PBR bake of the committed blend, and actual GLB reimport was reviewed.'},
 'rights':{'checked_at':'2026-09-09','terms_url':'https://higgsfield.ai/terms-of-use-agreement','terms_section':'4.4 User Inputs and Outputs','help_url':'https://higgsfield.ai/creator-hub/help-center/account/who-owns-my-generations-and-can-i-use-them-commercially','summary':'Higgsfield does not claim ownership of inputs/outputs or restrict commercial use of outputs; exported rights survive subscription cancellation/account deletion. Terms do not guarantee uniqueness or exclusive copyright.','external_asset_licenses':[]},
 'derivative':{'primary':manifest['primary'],'baked_workfile':hash_file('shrine-baked-workfile.blend'),'png_master':hash_file('shrine-combined-baked.glb'),'recipes':[hash_file(f) for f in ['prepare_runtime.py','package_runtime.mjs','validate_runtime.mjs','render_runtime.py','finalize_ledger.py']],'tool_versions':{'blender':'5.2.1 LTS',**versions},'runtime_materials':2,'shared_runtime_textures':4,'lod_triangles':[5936,2944,1134],'draws_per_selected_lod':2,'anchors':manifest['anchors_gltf'],'lights':0,'rgba8_mip_memory_estimate_bytes':manifest['mobileEstimatedRgba8MipBytes']},
 'validation':{'geometry_equal_across_variants':audit['geometryEqual'],'geometry_sha256':audit['variants']['compressed']['geometrySha256'],'decoded_gltf_errors':0,'decoded_gltf_warnings':0,'encoded_compressed_errors':0,'encoded_compressed_warnings':6,'encoded_warning_explanation':'Installed glTF validator does not recognize KTX2 MIME/format (six warnings) or Meshopt/Basisu extensions (infos). Actual decoded derivatives both validate cleanly.','audit':'final-export-audit.json','runtime_manifest':'runtime-manifest.json','texture_mae_8bit':audit['textureMeanAbsoluteError8Bit']},
 'visual_qa':{'reviewed':['cloud-source-review.png','cloud-glb-review.png','baked-lod0-review.png','fallback-lod0-review.png','compressed-lod0-review.png','compressed-lod1-review.png','compressed-lod2-review.png','compressed-cyan-review.png','compressed-off-review.png'],'result':'Portable compressed and PNG exports preserve layered stone and forged rim; lower LODs retain silhouette, with coarse LOD2 reserved for distance. Cyan/off tests preserve stone and control only emissive surfaces.','connector_limitation':'query_python and show_scene were not exposed. No claim to have used them. Actual source download, remote generated preview, operation metadata and local actual-export reimports were inspected.','integration_qa':'Game/browser/mobile performance validation belongs to integrating task; this package makes no phone performance claim.'}
}
write('production-ledger.json',ledger)
inventory=[]
for p in sorted(P.rglob('*')):
 if p.is_file() and '__pycache__' not in str(p) and p.name!='SHA256SUMS.json':inventory.append(hash_file(str(p.relative_to(P))))
write('SHA256SUMS.json',{'algorithm':'SHA-256','files':inventory})
print(json.dumps({'ready':True,'runtime':entry,'source':ledger['source'],'files':len(inventory),'bytes':sum(x['bytes'] for x in inventory)},indent=2))
