/** Extract real knee-local foot support caches and sample all locomotion keys. No asset mutation. */
import fs from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';
const argv=process.argv.slice(2),arg=(n,d)=>argv.includes(n)?argv[argv.indexOf(n)+1]:d,game=arg('--game'),out=arg('--out'),candidate=arg('--candidate');
if(!game||!out||!candidate)throw Error('Supply --game --out --candidate');
const imp=p=>import(pathToFileURL(path.join(game,'node_modules',p)));
const [{NodeIO},{ALL_EXTENSIONS},{MeshoptDecoder},T]=await Promise.all([imp('@gltf-transform/core/dist/index.js'),imp('@gltf-transform/extensions/dist/index.js'),imp('meshoptimizer/index.js'),imp('three/build/three.module.js')]);
await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder});
const manifest=JSON.parse(await fs.readFile(path.join(game,'public/assets/characters/v10/manifest.json'),'utf8'));
const sources=['ash-knight','crypt-warden','ember-sovereign'].map(id=>({id,path:id==='ember-sovereign'?candidate:path.join(game,'public',manifest.characters[id].variants.mobile.url)}));
const round=v=>typeof v==='number'?Number(v.toFixed(7)):v.map(round),V=v=>new T.Vector3().fromArray(v),M=v=>new T.Matrix4().fromArray(v);
function sample(doc,rest,clip,time){for(const x of rest)x.n.setTranslation(x.t).setRotation(x.r).setScale(x.s);if(!clip)return;const anim=doc.getRoot().listAnimations().find(x=>x.getName()===clip);for(const ch of anim.listChannels()){const s=ch.getSampler(),i=s.getInput(),o=s.getOutput();let hi=1;while(hi<i.getCount()-1&&i.getScalar(hi)<time)hi++;let lo=hi-1,t=Math.max(0,Math.min(1,(time-i.getScalar(lo))/(i.getScalar(hi)-i.getScalar(lo))));if(s.getInterpolation()==='STEP')t=0;const aa=o.getElement(lo,[]),bb=o.getElement(hi,[]),n=ch.getTargetNode();if(ch.getTargetPath()==='rotation')n.setRotation(new T.Quaternion().fromArray(aa).slerp(new T.Quaternion().fromArray(bb),t).toArray());else if(ch.getTargetPath()==='translation')n.setTranslation(aa.map((x,k)=>x+(bb[k]-x)*t));else if(ch.getTargetPath()==='scale')n.setScale(aa.map((x,k)=>x+(bb[k]-x)*t));}}
const results=[];
for(const source of sources){
 const doc=await io.read(source.path),root=doc.getRoot(),lod=root.listNodes().find(n=>n.getExtras().lod===0),skin=lod.getSkin(),joints=skin.listJoints(),nodes=root.listNodes(),rest=nodes.map(n=>({n,t:n.getTranslation(),r:n.getRotation(),s:n.getScale()}));
 const indices=new Map(joints.map((n,i)=>[n.getName(),i])),ibm=skin.getInverseBindMatrices(),body=joints.find(j=>j.getName()==='body');
 const times=[{clip:null,time:0,label:'neutral'}];for(const clip of ['idle','forward','backward','strafe_left','strafe_right','turn']){const anim=root.listAnimations().find(a=>a.getName()===clip);if(!anim)continue;const t=[...new Set(anim.listSamplers().flatMap(s=>Array.from(s.getInput().getArray())))].sort((a,b)=>a-b);for(const time of t)times.push({clip,time});}
 const legs=[];
 for(const side of ['left','right']){
  const hip=joints[indices.get(side+'_leg')],knee=joints[indices.get(side+'_knee')],ji=indices.get(side+'_knee'),inverseBind=M(ibm.getElement(ji,[])),hipWorld=M(hip.getWorldMatrix()),kneeWorld=M(knee.getWorldMatrix());
  const all=[];for(const p of lod.getMesh().listPrimitives()){const pos=p.getAttribute('POSITION'),js=p.getAttribute('JOINTS_0'),ws=p.getAttribute('WEIGHTS_0');for(let i=0;i<pos.getCount();i++){const j=js.getElement(i,[]),w=ws.getElement(i,[]);if(j.some((x,k)=>x===ji&&w[k]>.999)){const local=V(pos.getElement(i,[])).applyMatrix4(inverseBind),world=local.clone().applyMatrix4(kneeWorld);all.push({local,world});}}}
  const minY=Math.min(...all.map(v=>v.world.y)),foot=all.filter(v=>v.world.y<minY+.28),seen=new Set(),points=foot.filter(v=>{const key=v.local.toArray().map(x=>x.toFixed(6)).join(',');if(seen.has(key))return false;seen.add(key);return true;});
  const minWorld=(matrix)=>{let min=Infinity,index=-1;for(let i=0;i<points.length;i++){const y=points[i].local.clone().applyMatrix4(matrix).y;if(y<min){min=y;index=i;}}return {min,index};};
  const samples=times.map(c=>{sample(doc,rest,c.clip,c.time);const km=M(knee.getWorldMatrix()),hp=V(hip.getWorldTranslation()),kp=V(knee.getWorldTranslation());return {...c,kneeWorld:km,hipY:hp.y,kneeY:kp.y,actual:minWorld(km)};});
  // Greedy support cache: include neutral minimum then the largest missed support.
  const selected=new Set([samples[0].actual.index]);let maxError=Infinity;while(selected.size<16){let worst=null;maxError=0;for(const s of samples){const proxyMin=Math.min(...[...selected].map(i=>points[i].local.clone().applyMatrix4(s.kneeWorld).y)),error=proxyMin-s.actual.min;if(error>maxError){maxError=error;worst=s;}}if(maxError<.00025||!worst)break;selected.add(worst.actual.index);}
  sample(doc,rest,null,0);const sole=points.filter(v=>v.world.y<minY+.025),soleBounds=new T.Box3();for(const v of sole)soleBounds.expandByPoint(v.world);const center=soleBounds.getCenter(new T.Vector3());center.y=minY;const localCenter=center.clone().applyMatrix4(kneeWorld.clone().invert());const hipToKnee=V(knee.getWorldTranslation()).sub(V(hip.getWorldTranslation()));
  legs.push({side,hipBone:hip.getName(),kneeBone:knee.getName(),hipParent:hip.getParentNode()?.getName(),kneeParent:knee.getParentNode()?.getName(),hipRestLocal:{translation:hip.getTranslation(),rotation:hip.getRotation(),scale:hip.getScale()},kneeRestLocal:{translation:knee.getTranslation(),rotation:knee.getRotation(),scale:knee.getScale()},hipWorldRest:round(hip.getWorldTranslation()),kneeWorldRest:round(knee.getWorldTranslation()),hipToKneeLocalAxis:round(V(knee.getTranslation()).normalize().toArray()),upperLegLengthMetres:round(hipToKnee.length()),kneeToSoleCenterLocal:round(localCenter.toArray()),kneeToSoleCenterLocalAxis:round(localCenter.clone().normalize().toArray()),kneeToSoleCenterRestDistanceMetres:round(localCenter.length()),soleBoundsRest:{min:round(soleBounds.min.toArray()),max:round(soleBounds.max.toArray())},restSoleMinimumY:round(minY),footUniqueVertices:points.length,rigidKneeWeightThreshold:.999,footRegionRestHeightMetres:.28,proxyLocalPoints:[...selected].map(i=>round(points[i].local.toArray())),proxyCount:selected.size,maximumProxySupportOverestimateMetres:round(maxError),inverseBindMatrix:round(inverseBind.elements),groundSamples:samples.map(s=>({clip:s.clip,time:round(s.time),hipY:round(s.hipY),kneeY:round(s.kneeY),actualFootMinY:round(s.actual.min),proxyMinY:round(Math.min(...[...selected].map(i=>points[i].local.clone().applyMatrix4(s.kneeWorld).y)))}))});
 }
 sample(doc,rest,null,0);
 results.push({id:source.id,source:source.path,units:'Unscaled actor/model metres; multiply by actor.group scale for world errors',jointCount:joints.length,restBodyLocal:{translation:body.getTranslation(),rotation:body.getRotation(),scale:body.getScale()},restBodyWorld:round(body.getWorldTranslation()),meshNodeLocal:{translation:lod.getTranslation(),rotation:lod.getRotation(),scale:lod.getScale()},positionAccessors:lod.getMesh().listPrimitives().map(p=>({componentType:p.getAttribute('POSITION').getComponentType(),normalized:p.getAttribute('POSITION').getNormalized()})),legs});
 console.log(source.id,legs.map(l=>({side:l.side,proxyCount:l.proxyCount,maxProxyError:l.maximumProxySupportOverestimateMetres,minGround:Math.min(...l.groundSamples.map(s=>s.actualFootMinY)),maxGround:Math.max(...l.groundSamples.map(s=>s.actualFootMinY))})));
}
await fs.writeFile(out,JSON.stringify({method:'Knee-rigid vertices from actual decoded LOD0. Inverse bind transforms normalized raw positions to knee-local physical coordinates, including quantization compensation. Foot region is below rest sole minimum +0.28m. Greedy extrema cache validated against all full-foot vertices at every authored idle/walk/turn key, with 0.25mm target tolerance and maximum16 points. No runtime per-frame vertex scan required.',limitations:['No ankle or foot joints exist. Knee-to-sole distance is a virtual contact segment, not an anatomical shin length.','Ground sample values are uncorrected model-space minimum foot heights, not stance errors: elevated swing feet should not be forcibly planted.','Cached extrema prove support at sampled keys; dense interpolation and runtime blended poses need validation.','Sovereign source is refined uncompressed master; other assets are current decoded mobile variants. Use runtime skeleton bone.matrixWorld plus the supplied knee-local points; do not apply quantized mesh scale a second time.'],assets:results},null,2)+'\n');
